In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [34]:
import pandas as pd

In [7]:
df_copy = pd.read_json("C:/Users/ASUS/Downloads/hackathon/messages.json")

In [35]:
df = df_copy

In [38]:
df_copy

,userId,exportDate,conversations
0,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.2ce9f8dccf1fc085', 'displa..."
1,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.78533d4cb35406cc', 'displa..."
2,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.a4c67d0b2e72bac6', 'displa..."
3,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.354621f1f9cfe2ea', 'displa..."
4,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:mayanktamboli', 'displayName': ..."
...,...,...,...
16284,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:8922232643a2326e', 'displayName..."
16285,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.fe63248b85b39c2f', 'displa..."
16286,8:live:.cid.4933a22bf564744,2022-06-11T00:06,{'id': '19:f2ab5c3e027a47009d34577d97680048@th...
16287,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:amudgal76', 'displayName': 'Ash..."
16288,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:malay82', 'displayName': 'tanu ..."

In [85]:
print(df_copy['conversations'][566])

{'id': '19:898baf6f5680724aea0b3884b966963e92c72d6f2b52603c40ffd123c201df35@encrypted.skype', 'displayName': 'live:.cid.4933a22bf564744, live:.cid.2119caa810730412', 'version': 1654168231927.0, 'properties': {'conversationblocked': False, 'lastimreceivedtime': '2022-06-02T10:44:59.951Z', 'consumptionhorizon': '1649332120007;1652946922209;1649332120007', 'conversationstatus': None}, 'threadProperties': {'membercount': 2, 'members': '["8:live:.cid.4933a22bf564744","8:live:.cid.2119caa810730412"]', 'topic': 'live:.cid.4933a22bf564744, live:.cid.2119caa810730412', 'picture': None, 'description': None, 'guidelines': None}, 'MessageList': []}

In [86]:
dict = []
for i in range(len(df_copy['conversations'])):
    dict.append(df['conversations'][i]['MessageList'])

In [87]:
type(dict)

list

In [78]:
# len(dict)
# dict[0][len(dict[0])-1]['content']

'<ss type="hi">(wave)</ss>'

In [74]:
# dict = df['conversations'][1]['MessageList']
# len(dict)

319

In [102]:
list_content = []
list_label = []
for j in range(len(dict)):
    if len(dict[j])!=0:
        list_content.append(dict[j][len(dict[j])-1]['content'])
        if dict[j][len(dict[j])-1]['displayName'] ==None:
            list_label.append(1)
        else:
            list_label.append(0)
        for i in range(len(dict[j])-2,-1,-1):
        #     if dict[i]['messagetype']=='RichText':
                if dict[j][i+1]['displayName']==dict[j][i]['displayName']:
                    list_content[-1] = list_content[-1] + ' ' + dict[j][i]['content']
                else:
                    list_content.append(dict[j][i]['content'])
                    if dict[j][i]['displayName'] ==None:
                        list_label.append(1)
                    else:
                        list_label.append(0)

KeyboardInterrupt:

In [75]:
# list_content = []
# list_label = []
# list_content.append(dict[318]['content'])
# if dict[318]['displayName'] ==None:
#     list_label.append(1)
# else:
#     list_label.append(0)
# for i in range(len(dict)-2,-1,-1):
# #     if dict[i]['messagetype']=='RichText':
#         if dict[i+1]['displayName']==dict[i]['displayName']:
#             list_content[-1] = list_content[-1] + ' ' + dict[i]['content']
#         else:
#             list_content.append(dict[i]['content'])
#             if dict[i]['displayName'] ==None:
#                 list_label.append(1)
#             else:
#                 list_label.append(0)

In [89]:
df = pd.DataFrame({'lst1Tite' : list_label, 'lst2Tite' : list_content})

In [94]:
len(df['lst2Tite'])

1034379

In [92]:
df.to_csv('whole_data_hackathon.csv')

In [114]:
df = pd.read_csv('data_hackathon2.csv')

In [119]:
# del df['Unnamed:0']
df

     lst1Tite                                           lst2Tite
0           0  Hello I have enrolled in the Machine Learning ...
1           1                         Kindly check your mail sir
2           0  I already checked it there is no mail for the ...
3           1  <a href="https://zoom.us/j/96193473094">https:...
4           0                                          Thank you
..        ...                                                ...
180         0  Is the degree compulsory for most of the compa...
181         1  I guess so at least a bachelor degree might be...
182         0  Ok sir. Sir is ineuron coming up with full sta...
183         1              Big Data Course will be launched soon
184         0                                                 ok

[185 rows x 2 columns]

In [14]:
for i in range(len(df)):
    print(df.iloc[i])

lst1Tite                                                    0
lst2Tite    Hello I have enrolled in the Machine Learning ...
Name: 0, dtype: object
lst1Tite                             1
lst2Tite    Kindly check your mail sir
Name: 1, dtype: object
lst1Tite                                                    0
lst2Tite    I already checked it there is no mail for the ...
Name: 2, dtype: object
lst1Tite                                                    1
lst2Tite    <a href="https://zoom.us/j/96193473094">https:...
Name: 3, dtype: object
lst1Tite            0
lst2Tite    Thank you
Name: 4, dtype: object
lst1Tite                      1
lst2Tite    You&apos;re welcome
Name: 5, dtype: object
lst1Tite                                                    0
lst2Tite    It is showing that The host has another meetin...
Name: 6, dtype: object
lst1Tite                        1
lst2Tite    10 pm is the time sir
Name: 7, dtype: object
lst1Tite                        0
lst2Tite    Ok so I cant join now
Name: 8, dtype: object
lst1Tite          1
lst2Tite    Yes sir
Name: 9, dtype: object
lst1Tite                                                    0
lst2Tite        <URIObject uri="https://api.asm.skype.com/...
Name: 10, dtype: object
lst1Tite                        1
lst2Tite    There is no error sir
Name: 11, dtype: object
lst1Tite                                                    0
lst2Tite    The last cell never stops running and I can&ap...
Name: 12, dtype: object
lst1Tite                                         1
lst2Tite    Click on the url that it has generated
Name: 13, dtype: object
lst1Tite                                       0
lst2Tite    Yes i did that but it is not working
Name: 14, dtype: object
lst1Tite                                                    1
lst2Tite    Download the project in your system and run it...
Name: 15, dtype: object
lst1Tite                                                   0
lst2Tite    Ok sir Is Doubt Clearing session started or not?
Name: 16, dtype: object
lst1Tite                                 1
lst2Tite    You&apos;re in which batch sir
Name: 17, dtype: object
lst1Tite                      0
lst2Tite    10th april ML batch
Name: 18, dtype: object
lst1Tite                                                    1
lst2Tite    <a href="https://zoom.us/j/98988249200">https:...
Name: 19, dtype: object
lst1Tite                                                 0
lst2Tite    Please wait for the host to start this webinar
Name: 20, dtype: object
lst1Tite                                                    1
lst2Tite    <quote author="live:.cid.4933a22bf564744" auth...
Name: 21, dtype: object
lst1Tite                                0
lst2Tite    Zoom is showing this Ok sorry
Name: 22, dtype: object
lst1Tite                                                   1
lst2Tite    No problem Kindly check your mail frequently sir
Name: 23, dtype: object
lst1Tite                          0
lst2Tite    Yes sir Thank you again
Name: 24, dtype: object
lst1Tite                                     1
lst2Tite    You&apos;re welcome Happy learning
Name: 25, dtype: object
lst1Tite                                                    0
lst2Tite    Is their any meeting id for joining the today&...
Name: 26, dtype: object
lst1Tite                                                    1
lst2Tite    I think its working now, kindly let me know if...
Name: 27, dtype: object
lst1Tite                                                    0
lst2Tite    <a href="https://carprice-prediction-gs.heroku...
Name: 28, dtype: object
lst1Tite                                                    1
lst2Tite    <quote author="live:.cid.78533d4cb35406cc" aut...
Name: 29, dtype: object
lst1Tite                                          0
lst2Tite    yes it is one of the dependent variable
Name: 30, dtype: object
lst1Tite                                                    1
lst2Tite    Sir it if prediction you are getting desired o...
Name: 31, dtype: object
lst1Tite                                                    0
lst2Tite    <URIObject uri="https://api.asm.skype.com/v1/o...
Name: 32, dtype: object
lst1Tite                                              1
lst2Tite    yes sir for sure you must use other ml algo
Name: 33, dtype: object
lst1Tite            0
lst2Tite    ok thanks
Name: 34, dtype: object
lst1Tite                      1
lst2Tite    you&apos;re welcome
Name: 35, dtype: object
lst1Tite                                                    0
lst2Tite    Hello sir Can you suggest me best book for ref...
Name: 36, dtype: object
lst1Tite                                          1
lst2Tite    HandsonMachine-Learning-with-Scikit-2E
Name: 37, dtype: object
lst1Tite                                                    0
lst2Tite    OK sir Hello sir,\nI have one ML problem, can ...
Name: 38, dtype: object
lst1Tite                                      1
lst2Tite    You can use clustering approach sir
Name: 39, dtype: object
lst1Tite                                                    0
lst2Tite    ok sir ERROR: Command errored out with exit st...
Name: 40, dtype: object
lst1Tite                                         1
lst2Tite    Hello sir please elaborate your query
Name: 41, dtype: object
lst1Tite                                                    0
lst2Tite    I am deploying ML app with streamlit on heroku...
Name: 42, dtype: object
lst1Tite                                        1
lst2Tite    in your local system its wkring sir??
Name: 43, dtype: object
lst1Tite                                               0
lst2Tite    Yes it is working perfectly on local system.
Name: 44, dtype: object
lst1Tite                                                    1
lst2Tite    <a href="https://www.youtube.com/watch?v=hPst9...
Name: 45, dtype: object
lst1Tite                            0
lst2Tite    ok I&apos;ll try this way
Name: 46, dtype: object
lst1Tite           1
lst2Tite    sure sir
Name: 47, dtype: object
lst1Tite                                                    0
lst2Tite    Hello sir <quote author="live:.cid.4933a22bf56...
Name: 48, dtype: object
lst1Tite                                                    1
lst2Tite    show me your requriments.txt file screenshit s...
Name: 49, dtype: object
lst1Tite                                                    0
lst2Tite    ok <URIObject uri="https://api.asm.skype.com/v...
Name: 50, dtype: object
lst1Tite                                                    1
lst2Tite    <quote author="live:.cid.4933a22bf564744" auth...
Name: 51, dtype: object
lst1Tite                                                    0
lst2Tite     Getting requirements to build wheel: started\...
Name: 52, dtype: object
lst1Tite                                1
lst2Tite    Okay sir wait looking into it
Name: 53, dtype: object
lst1Tite                   0
lst2Tite    ok sir thank you
Name: 54, dtype: object
lst1Tite                                                    1
lst2Tite    try pip install wheel sir and try again instal...
Name: 55, dtype: object
lst1Tite                                                    0
lst2Tite    ok  I tried that way to deploy but it failed a...
Name: 56, dtype: object
lst1Tite                                                    1
lst2Tite    send error sir<e_m a="live:.cid.4933a22bf56474...
Name: 57, dtype: object
lst1Tite                                                    0
lst2Tite    <URIObject uri="https://api.asm.skype.com/v1/o...
Name: 58, dtype: object
lst1Tite                                   1
lst2Tite    have you installed in same path?
Name: 59, dtype: object
lst1Tite          0
lst2Tite    yes sir
Name: 60, dtype: object
lst1Tite                                                    1
lst2Tite    can you send ss when you installed what came w...
Name: 61, dtype: object
lst1Tite                                      0
lst2Tite    Image classification with Streamlit
Name: 62, dtype: object
lst1Tite                                               1
lst2Tite    which python version have you used hare sir?
Name: 63, dtype: object
lst1Tite      0
lst2Tite    3.8
Name: 64, dtype: object
lst1Tite                     1
lst2Tite    try to use 3.6 sir
Name: 65, dtype: object
lst1Tite                                                    0
lst2Tite    I have used conda environment ok sir Sir my st...
Name: 66, dtype: object
lst1Tite                                 1
lst2Tite    What issues are you facing sir
Name: 67, dtype: object
lst1Tite                                          0
lst2Tite    Same issue as above I mentioned earlier
Name: 68, dtype: object
lst1Tite                                     1
lst2Tite    can you write your query again sir
Name: 69, dtype: object
lst1Tite                                                    0
lst2Tite    What to do sir if our regularized Linear Regre...
Name: 70, dtype: object
lst1Tite                                                    1
lst2Tite    then in that case you will have to check with ...
Name: 71, dtype: object
lst1Tite                                                    0
lst2Tite    So I have to perform feature engineering and f...
Name: 72, dtype: object
lst1Tite          1
lst2Tite    yes sir
Name: 73, dtype: object
lst1Tite                   0
lst2Tite    ok sir thank you
Name: 74, dtype: object
lst1Tite               1
lst2Tite    welcome sir
Name: 75, dtype: object
lst1Tite                                                    0
lst2Tite    Sir how can I solve the below problem?\nPredic...
Name: 76, dtype: object
lst1Tite                                                    1
lst2Tite    sir there no any specific algorithms that can ...
Name: 77, dtype: object
lst1Tite                                                    0
lst2Tite    Yes I have done EDA and data preprocessing but...
Name: 78, dtype: object
lst1Tite                                                    1
lst2Tite    try with some algorithm and analyses their  ac...
Name: 79, dtype: object
lst1Tite                                                    0
lst2Tite    Hello sir, I am trying to solve a regression p...
Name: 80, dtype: object
lst1Tite                                                    1
lst2Tite    sir It seems that your number of training samp...
Name: 81, dtype: object
lst1Tite                           0
lst2Tite    So what is the solution?
Name: 82, dtype: object
lst1Tite                                                    1
lst2Tite    try to reshape it according to ur x_train and ...
Name: 83, dtype: object
lst1Tite                                                    0
lst2Tite    Thank you i solved it   Hello sir, I am have o...
Name: 84, dtype: object
lst1Tite                                                  1
lst2Tite    sir our tech team on leave today and  tomorrow
Name: 85, dtype: object
lst1Tite                                                    0
lst2Tite    ok sir   Hello sir, I am have one task where I...
Name: 86, dtype: object
lst1Tite                                                    1
lst2Tite    <a href="https://github.com/LaxmiChaudhary/Amz...
Name: 87, dtype: object
lst1Tite                                                    0
lst2Tite    Hello sir, I am have one task where I ave to b...
Name: 88, dtype: object
lst1Tite                                                    1
lst2Tite    please check in dashboard there are multiple e...
Name: 89, dtype: object
lst1Tite                                                    0
lst2Tite    Yeah there are multiple machine learning proje...
Name: 90, dtype: object
lst1Tite                                             1
lst2Tite    all are end to end projects please explore
Name: 91, dtype: object
lst1Tite                                                    0
lst2Tite    I have explored all the projects but there is ...
Name: 92, dtype: object
lst1Tite                                                    1
lst2Tite    ok let me check we don&apos;t have pls create ...
Name: 93, dtype: object
lst1Tite                                                    0
lst2Tite    ok sir  <URIObject uri="https://api.asm.skype....
Name: 94, dtype: object
lst1Tite                                                  1
lst2Tite    Is this project from Ineuron internship portal?
Name: 95, dtype: object
lst1Tite     0
lst2Tite    No
Name: 96, dtype: object
lst1Tite                              1
lst2Tite    can we have quick call sir
Name: 97, dtype: object
lst1Tite                         0
lst2Tite    ok on skype or mobile?
Name: 98, dtype: object
lst1Tite                                                    1
lst2Tite    is it interview question? please mention the s...
Name: 99, dtype: object
lst1Tite                                0
lst2Tite    no it is a hackathon question
Name: 100, dtype: object
lst1Tite                                                  1
lst2Tite    sorry we cant help in hackathon and assignments
Name: 101, dtype: object
lst1Tite                                                    0
lst2Tite    Its not a ineuron hackathon It is a Analytics ...
Name: 102, dtype: object
lst1Tite                                                   1
lst2Tite    sorry sir, we can&apos;t help you in assignment
Name: 103, dtype: object
lst1Tite                                                    0
lst2Tite    ok So how can I learn solving this type of pro...
Name: 104, dtype: object
lst1Tite                                                    1
lst2Tite    try to solve intership problems then you will ...
Name: 105, dtype: object
lst1Tite                                                    0
lst2Tite    but thats what I am asking na that how to solv...
Name: 106, dtype: object
lst1Tite                                                    1
lst2Tite    focus on aptitude and logical reasoning questi...
Name: 107, dtype: object
lst1Tite                                             0
lst2Tite    hi I have one dubt in rasa chatbot project
Name: 108, dtype: object
lst1Tite                   1
lst2Tite    please ask sir\n
Name: 109, dtype: object
lst1Tite                                                    0
lst2Tite    I wanted to build a bot like amazon bot. I hav...
Name: 110, dtype: object
lst1Tite                             1
lst2Tite    what do you mean by button
Name: 111, dtype: object
lst1Tite                                                    0
lst2Tite    button means if I click on that order so all t...
Name: 112, dtype: object
lst1Tite            1
lst2Tite    hello sir
Name: 113, dtype: object
lst1Tite                                  0
lst2Tite    I have asked you about the rasa
Name: 114, dtype: object
lst1Tite                                 1
lst2Tite    please mention your batch name
Name: 115, dtype: object
lst1Tite             0
lst2Tite    MLDL batch
Name: 116, dtype: object
lst1Tite                                              1
lst2Tite    okay. Could you please elaborate your query
Name: 117, dtype: object
lst1Tite                                                    0
lst2Tite    14:11\nI wanted to build a bot like amazon bot...
Name: 118, dtype: object
lst1Tite                                                    1
lst2Tite    using SQL queries you can fetch data from resp...
Name: 119, dtype: object
lst1Tite                                                    0
lst2Tite    I have no problem in fetching the data but I h...
Name: 120, dtype: object
lst1Tite                                       1
lst2Tite    please copy paste your error message
Name: 121, dtype: object
lst1Tite                                                    0
lst2Tite    I am not getting any error but the data is not...
Name: 122, dtype: object
lst1Tite                                                    1
lst2Tite    create the dataframe using this values and sel...
Name: 123, dtype: object
lst1Tite               0
lst2Tite    Ok Thank you
Name: 124, dtype: object
lst1Tite          1
lst2Tite    welcome
Name: 125, dtype: object
lst1Tite                                                    0
lst2Tite    But if there more products it will be not read...
Name: 126, dtype: object
lst1Tite                                       1
lst2Tite    it will depend upon your code format
Name: 127, dtype: object
lst1Tite                                                    0
lst2Tite    ok Hello sir Good Morning I have one doubt in ...
Name: 128, dtype: object
lst1Tite                                         1
lst2Tite    good morning sir please ask your doubt
Name: 129, dtype: object
lst1Tite                                                    0
lst2Tite    Ok So i am working with date type variables. I...
Name: 130, dtype: object
lst1Tite                                                    1
lst2Tite    which kind of error it is showing in pycharm s...
Name: 131, dtype: object
lst1Tite                                                    0
lst2Tite    ok <URIObject uri="https://api.asm.skype.com/v...
Name: 132, dtype: object
lst1Tite                                                    1
lst2Tite    sir pycharm and jupyter works on different pla...
Name: 133, dtype: object
lst1Tite                                                    0
lst2Tite    <URIObject uri="https://api.asm.skype.com/v1/o...
Name: 134, dtype: object
lst1Tite                                                    1
lst2Tite    sir the error is coming from line after read c...
Name: 135, dtype: object
lst1Tite                                                    0
lst2Tite    yeah that i know but the same code is running ...
Name: 136, dtype: object
lst1Tite                                                    1
lst2Tite    get index location of rows which match the con...
Name: 137, dtype: object
lst1Tite                                                    0
lst2Tite    <URIObject uri="https://api.asm.skype.com/v1/o...
Name: 138, dtype: object
lst1Tite        1
lst2Tite    wait
Name: 139, dtype: object
lst1Tite     0
lst2Tite    Ok
Name: 140, dtype: object
lst1Tite                          1
lst2Tite    can yu send me the link
Name: 141, dtype: object
lst1Tite                                                    0
lst2Tite    <a href="https://meet.google.com/jvd-eejo-gdf"...
Name: 142, dtype: object
lst1Tite          1
lst2Tite    welcome
Name: 143, dtype: object
lst1Tite                                                    0
lst2Tite    <URIObject uri="https://api.asm.skype.com/v1/o...
Name: 144, dtype: object
lst1Tite                           1
lst2Tite      classification problem
Name: 145, dtype: object
lst1Tite                                      0
lst2Tite    Time series classification problem?
Name: 146, dtype: object
lst1Tite                   1
lst2Tite    yes kind of that
Name: 147, dtype: object
lst1Tite                                                    0
lst2Tite    Can you provide any resource about this sir? I...
Name: 148, dtype: object
lst1Tite                                 1
lst2Tite    wait  i have to think on these
Name: 149, dtype: object
lst1Tite                                                    0
lst2Tite    Ok sir I will wait for your response Sorry for...
Name: 150, dtype: object
lst1Tite                                   1
lst2Tite    no worries send ur data will try
Name: 151, dtype: object
lst1Tite                                              0
lst2Tite    Sorry sir I dont have the dataset right now
Name: 152, dtype: object
lst1Tite                                    1
lst2Tite    you can search over the internet
Name: 153, dtype: object
lst1Tite            0
lst2Tite    Hello sir
Name: 154, dtype: object
lst1Tite     1
lst2Tite    hi
Name: 155, dtype: object
lst1Tite                                                    0
lst2Tite    I am stuck in a situation where I want some ca...
Name: 156, dtype: object
lst1Tite                                        1
lst2Tite    what carrear guidance do you need sir
Name: 157, dtype: object
lst1Tite                                                    0

In [101]:
df

         lst1Tite                                           lst2Tite
0               0                                       wave  hi sir
1               1                                           hi&apos;
2               0                                               sir
3               1                                             hello
4               0  i have completed the excel course where i need...
...           ...                                                ...
1034374         0  <partlist type="started" alt=""><part identity...
1034375         1  <addmember><eventtime>1587277641886</eventtime...
1034376         0  <ss type="hi">(wave)</ss> Hi \nFor any CNN mod...
1034377         1  The lenet has a specific architecture....but y...
1034378         0  <ss type="hi">(wave)</ss> testing the message....

[1034379 rows x 2 columns]

In [120]:
import re    # regular expression
from nltk.corpus import stopwords

# set of stop words
stop = set(stopwords.words('english')) 

def remove_stop(word):
    if word not in stop:
        return word
    return ''
        
def lower_text(sentence):
    sentence=sentence.lower()
    return sentence

def cleanhtml(sentence):
    cleanr = re.compile('<.*?>')  # any thing in angular brackets
    cleantext = re.sub(cleanr, 'link', sentence) # replace with
    return cleantext

def cleanpunc(sentence):
    cleaned = re.sub(r'[?|!|\'|"|#]',r'', sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    return cleaned

In [122]:
for i in range(len(df['lst2Tite'])):
#     print(df['lst2Tite'].iloc[i])
    df['lst2Tite'].iloc[i] = lower_text(df['lst2Tite'].iloc[i])
    df['lst2Tite'].iloc[i] = cleanpunc(df['lst2Tite'].iloc[i])
    df['lst2Tite'].iloc[i] = cleanhtml(df['lst2Tite'].iloc[i])

C:\Users\ASUS\AppData\Local\Temp/ipykernel_5044/3859319637.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lst2Tite'].iloc[i] = lower_text(df['lst2Tite'].iloc[i])
C:\Users\ASUS\AppData\Local\Temp/ipykernel_5044/3859319637.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lst2Tite'].iloc[i] = cleanpunc(df['lst2Tite'].iloc[i])
C:\Users\ASUS\AppData\Local\Temp/ipykernel_5044/3859319637.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lst2Tite'].iloc[i] = cleanhtml(df['lst2Tite'].iloc[i])

In [ ]:
df

In [99]:
# for i in range(len(df['lst2Tite'])):
#     #print(df['lst2Tite'].iloc[i])
#     df['lst2Tite'].iloc[i] = lower_text(df['lst2Tite'].iloc[i])
#     df['lst2Tite'].iloc[i] = cleanpunc(df['lst2Tite'].iloc[i])
#     df['lst2Tite'].iloc[i] = cleanhtml(df['lst2Tite'].iloc[i])

In [100]:
# df

In [29]:
for i in range(len(df['lst2Tite'])):
     df['lst2Tite'].iloc[i] = ' '.join(list(map(remove_stop, df['lst2Tite'].iloc[i].split())))

C:\Users\ASUS\AppData\Local\Temp/ipykernel_5044/624434393.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lst2Tite'].iloc[i] = ' '.join(list(map(remove_stop, df['lst2Tite'].iloc[i].split())))

In [30]:
df

     lst1Tite                                           lst2Tite
0           0  hello  enrolled machine learning  deep learnin...
1           1                              kindly check mail sir
2           0          already checked mail zoom link  send link
3           1                       https: zoom us j 96193473094
4           0                                              thank
..        ...                                                ...
180         0                degree compulsory company job roles
181         1   guess least bachelor degree might required ap...
182         0  ok sir sir ineuron coming full stack data engi...
183         1                      big data course launched soon
184         0                                                 ok

[185 rows x 2 columns]

In [131]:
# answer_df = df[df['lst1Tite']==1]
# question_df = df[df['lst1Tite']==0]

In [138]:
question_df
answer_df

     lst1Tite                                           lst2Tite
1           1                         kindly check your mail sir
3           1              linkhttps:  zoom us j 96193473094link
5           1                                you&apos;re welcome
7           1                              10 pm is the time sir
9           1                                            yes sir
..        ...                                                ...
175         1                                                 ok
177         1                              tell me what you need
179         1  no not required for the screening process but ...
181         1  i guess so at least a bachelor degree might be...
183         1              big data course will be launched soon

[92 rows x 2 columns]

In [140]:
question_df['lst2Tite'].to_list()

['hello i have enrolled in the machine learning and deep learning masters course \n can i have the link of today&apos;s doubt clearing session',
 'i already checked it there is no mail for the zoom link can you send the link',
 'thank you',
 'it is showing that the host has another meeting in progress',
 'ok so i cant join now',
 '    linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d8-a0e46ab5c998a652e9ddd3b9fb8bd5dblinklinklinklinklinklinklinklink sir i am facing issue in this code  if you can help in this please guide',
 'the last cell never stops running and i can&apos;t open the webapp ',
 'yes i did that but it is not working',
 'ok sir is doubt clearing session started or not',
 '10th april ml batch',
 'please wait for the host to start this webinar',
 'zoom is showing this ok sorry',
 'yes sir thank you again',
 'is their any meeting id for joining the today&apos;s zoom session i can&apos;t join today&apos;s 8 am class ok its working now thanks linkhttps:  github com gaurav21s carpricepredictionlink hello sir  this is my first end to end ml project   i followed krish sir&apos;s video for this but i am getting issues in the prediction  the selling price never give less than 1 lac or 0or negative even the present price is less than 1 or 0 lac  how can i fix this',
 'linkhttps:  carprice-prediction-gs herokuapp com link can you check this web app  the selling price is not giving the proper value according to condition when present price is 0 or negative  linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d8-310a800fbc6c252145487d3d0aef04eblinklinklinklinklinklinklinklink',
 'yes it is one of the dependent variable',
 'linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d7-4e8f60d9eac30aacecea358c99561040linklinklinklinklinklinklinklink this is my dependent variables ok do i need to use other ml algo to solve this',
 'ok thanks',
 'hello sir can you suggest me best book for reference for ml and dl',
 'ok sir hello sir \ni have one ml problem  can you suggest me how can i proceed with that i have a dataset that has user id  product  and the amount  and using this dataset  i have to predict for all the users in the training dataset  the top 3 categories that the user might buy from \n linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d2-8cf3a835d65c5c1f0e358271d68c34b2linklinklinklinklinklinklinklink',
 'ok sir error: command errored out with exit status 1:\n            command:  app  heroku python bin python  app  heroku python lib python3 9 site-packages pip _vendor pep517 _in_process py prepare_metadata_for_build_wheel  tmp tmp52l7599p\n                cwd:  tmp pip-install-k2jf35q_ pywinpty\n           complete output  6 lines :\n           checking for rust toolchain   \n           \n           cargo  the rust package manager  is not installed or is not on path \n           this package requires rust and cargo to compile extensions  install it through\n           the system&apos;s package manager or via linkhttps:  rustup rs link\n           \n           ----------------------------------------\n       error: command errored out with exit status 1:  app  heroku python bin python  app  heroku python lib python3 9 site-packages pip _vendor pep517 _in_process py prepare_metadata_for_build_wheel  tmp tmp52l7599p check the logs for full command output  i am facing this issue in heroku while deploying an app   can you help me to solve this',
 'i am deploying ml app with streamlit on heroku but it is giving me this error  linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d7-ae7825c932ffbd539f856097994e47celinklinklinklinklinklinklinklink',
 'yes it is working perfectly on local system ',
 'ok i&apos;ll try this way',
 'hello sir linklink[1625463319] support@ineuron ai: linklinkhttps:  www youtube com watchv=hpst9w_cpjq&amp;t=355slinklink\n\n&lt;&lt;&lt; linklinki followed the steps from this video but it is giving me the same issue linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d5-f3193ec10278534a16922434caa6d34alinklinklinklinklinklinklinklink',
 'ok linkto view this file  go to: linkhttps:  login skype com login ssogo=webclient xmm&amp;docid=0-sa-d5-98938b5da49319c529d4151faac7779alinklinklinklinklinklink',
 ' getting requirements to build wheel: started\nremote:          getting requirements to build wheel: finished with status &apos;done&apos;\nremote:            preparing wheel metadata: started\nremote:            preparing wheel metadata: finished with status &apos;error&apos;\nremote:            error: command errored out with exit status 1:\nremote:             command:  app  heroku python bin python  app  heroku python lib python3 9 site-packages pip _vendor pep517 _in_process py prepare_metadata_for_build_wheel  tmp tmpi_g_tsex\nremote:                 cwd:  tmp pip-install-u26f0pwl pywinpty\nremote:            complete output  6 lines :\nremote:            checking for rust toolchain   \nremote:\nremote:            cargo  the rust package manager  is not installed or is not on path \nremote:            this package requires rust and cargo to compile extensions  install it through\nremote:            the system&apos;s package manager or via linkhttps:  rustup rs link\nremote:\nremote:            ----------------------------------------\nremote:        error: command errored out with exit status 1:  app  heroku python bin python  app  heroku python lib python3 9 site-packages pip _vendor pep517 _in_process py prepare_metadata_for_build_wheel  tmp tmpi_g_tsex check the logs for full command output \nremote:       push rejected  failed to compile python app  this is the issue sir',
 'ok sir thank you',
 'ok  i tried that way to deploy but it failed again',
 'linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d1-09dcdc578e7af339b4831975f36e871elinklinklinklinklinklinklinklink same erroe sir error*',
 'yes sir',
 'image classification with streamlit',
 '3 8',
 'i have used conda environment ok sir sir my streamlit is not deploying on heroku ',
 'same issue as above i mentioned earlier',
 'what to do sir if our regularized linear regression model continues to show large errors',
 'so i have to perform feature engineering and feature scaling',
 'ok sir thank you',
 'sir how can i solve the below problem\npredict the store sales for each store in the test set for the next two months  linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d2-ad840e972257a0283aaa20e302249460linklinklinklinklinklinklinklink which ml algorithms can i use to solve this',
 'yes i have done eda and data preprocessing but i am not getting which algoritms or technique will work',
 'hello sir  i am trying to solve a regression problem with random forest but i am having some while fitting the data on training data but it is working well on full data  linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d7-9497f15ba58775751821b730406497e5linklinklinklinklinklinklinklink linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d5-1f84a68c7d8adb2f3fb5f0d6fec38cb5linklinklinklinklinklinklinklink',
 'so what is the solution',
 'thank you i solved it   hello sir  i am have one task where i ave to build end to end recommendation project but in the ineuron student dashboard there is no lecture or recordings for recommendation project and there is also no project about it  so can you help',
 'ok sir   hello sir  i am have one task where i ave to build end to end recommendation project but in the ineuron student dashboard there is no lecture or recordings for recommendation project and there is also no project about it  so can you help',
 'hello sir  i am have one task where i ave to build end to end recommendation project but in the ineuron student dashboard there is no lecture or recordings for recommendation project and there is also no project about it  so can you help thank you sir but this project is not end to end  please share any end to end recommendation project if possible  thank you for support',
 'yeah there are multiple machine learning project but there is not a recommendation end to end project ',
 'i have explored all the projects but there is no recommendation engine project in the dashboard  thank you sir  linklink[1635152811] support@ineuron ai: linkok let me checklink\n\n&lt;&lt;&lt; linklinksir have you checked',
 'ok sir  linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d8-90616040b6debb4f466abb5bf46ac697linklinklinklinklinklinklinklink linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d8-90616040b6debb4f466abb5bf46ac697linklinklinklinklinklinklinklink linklink linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d6-606341f1ce2a9f6b1c0d486176af84b5linklinklinklinklinklinklinklink can you suggest how to start with this problem',
 'no',
 'ok on skype or mobile',
 'no it is a hackathon question',
 'its not a ineuron hackathon it is a analytics vidhya hackathon problem',
 'ok so how can i learn solving this type of problem ',
 'but thats what i am asking na that how to solve this type of problem ',
 'hi i have one dubt in rasa chatbot project',
 'i wanted to build a bot like amazon bot  i have covered almost everything but in recent order or past order how do i convert the dataframe into button so the user can select the order which the user want to modify or change anything  so i am not getting how to do this i have already checked rasa documentation',
 'button means if i click on that order so all the details are shown to user like in amazon bot when bot shows the previous order we can select any order by clicking on them and it will show all the details for it hello sir',
 'i have asked you about the rasa',
 'mldl batch',
 '14:11\ni wanted to build a bot like amazon bot  i have covered almost everything but in recent order or past order how do i convert the dataframe into button so the user can select the order which the user want to modify or change anything  so i am not getting how to do this button means if i click on that order so all the details are shown to user\nlike in amazon bot when bot shows the previous order we can select any order by clicking on them and it will show all the details for it ignore 14 11',
 'i have no problem in fetching the data but i have got problem in showing the data',
 'i am not getting any error but the data is not in the readble format linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d2-3a7f97dc66f6af908e9f757b63049705linklinklinklinklinklinklinklink',
 'ok thank you',
 'but if there more products it will be not readable ',
 'ok hello sir good morning i have one doubt in the rasa chatbot project ',
 'ok so i am working with date type variables  i have performed the code in jupyter notebook and it runs successfully but the same code is not running successfully in pycharm  it is giving error  linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d5-6d48d7b0a6c26a325be82b8dbf8df1d9linklinklinklinklinklinklinklink',
 'ok linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d2-a3067926d2e86e45e4152bca730a09e1linklinklinklinklinklinklinklink it is giving the typeerror but the same code is running successfully in the jupyter',
 'linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d7-39390539499f5d9043b7507e0f099c08linklinklinklinklinklinklinklink this is the code',
 'yeah that i know but the same code is running successfully in the jupyter notebbok can you suggest how can i compare the value from the series',
 'linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d1-36b5ca1e63e3826f06229cdcd647529dlinklinklinklinklinklinklinklink hello sir  my resume discussion was scheduled on today at 4 to 6 pm with mr  sagar kandpal  but i cant join the google meet meeting with the shared link  is there any other meet link or is it rescheduled please inform ',
 'ok',
 'linkhttps:  meet google com jvd-eejo-gdflink i am in the meeting thank you',
 'linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d8-c19aca8ff7d2d00516d0c6de32ea242dlinklinklinklinklinklinklinklink linklink linkto view this shared photo  go to: linkhttps:  login skype com login ssogo=xmmfallbackpic=0-sa-d6-34cae7b19c313b749ab4a3a850fba538linklinklinklinklinklinklinklink linklink[1636704121] gaurav shrivastav: linkcan you suggest how to start with this problemlink\n\n&lt;&lt;&lt; linklink',
 'time series classification problem',
 'can you provide any resource about this sir i am not getting any idea how to start with this ',
 'ok sir i will wait for your response sorry for disturbing you at this time ',
 'sorry sir i dont have the dataset right now',
 'hello sir',
 'i am stuck in a situation where i want some career guidance ',
 'so sir   i was doing an machine learning internship at santa fe research pvt ltd  and they were offering me job after the internship between 5-6lpa  but like recently i was offered data science internship at roundglass and they are also offering job on the basis of performance in the internship  and company wise roundglass is very good company whereas santa fe research is not that big  so i was confused where should i go i am not decide which company to choose  i am not **able to decide santa fe research pvt ltd = linkhttps:  www linkedin com company santa-fe-research-private-limited link\nroundglass = linkhttps:  www linkedin com company roundglass link',
 'they are not saying about the package  they are saying it will be decide on the basis of performance in internship',
 'yeah they are saying they will offer that much and currently they are offering 12k  for internship and roundglass is offering 20k for the internship',
 'sir santa fe is a service based company and roundglass is a product based company ',
 'i was working with santa fe from last 2 and half month  they are very supporting and offering me help in the projects  but i didnt get interact with any data scientist there  and roundglass is like originally us company and very broad in terms of products  but i dont have any experience in roundglass ',
 'yeah i have contacted with them and one of them said this &quot;congrats for the offer  fundamentally this company is very strong and they will exponential growth  they have started using data science in their application  there is lot of opportunity to develop data science projects in this company &quot;',
 'ok',
 'ok sir hi sir',
 'i wanted to inquire about full stack data analytics course ',
 'for my small brother',
 'he just passed 12th is there a bachelor degree required for the job assistance program',
 'is the degree compulsory for most of the company for job roles',
 'ok sir  sir is ineuron coming up with full stack data engineering course',
 'ok']

In [ ]:
maxlen=1000
max_features=5000 
embed_size=300

#clean some null words or use the previously cleaned & lemmatized corpus
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
label_y= LabelEncoder()
train_y=label_y.fit_transform(answer_df['lst2Tite'])

train_x,test_x,train_y,test_y=train_test_split(question_df['lst2Tite'],train_y,test_size=0.2,random_state=42)

val_x = test_x
tokenizer=Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(train_x))
train_x=tokenizer.texts_to_sequences(train_x)
val_x=tokenizer.texts_to_sequences(val_x)

#Pad the sequence- To allow same length for all vectorized words
train_x=pad_sequences(train_x,maxlen=maxlen)
val_x=pad_sequences(val_x,maxlen=maxlen)
val_y=test_y
print("Padded and Tokenized Training Sequence".format(),train_x.shape)
print("Target Values Shape".format(),train_y.shape)
print("Padded and Tokenized Training Sequence".format(),val_x.shape)
print("Target Values Shape".format(),val_y.shape)

In [ ]:
model=Sequential()
model.add(Embedding(max_features,embed_size,input_length=maxlen))
model.add(LSTM(60))
model.add(Dense(16,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()
plot_model(
    model,
    to_file="simple_model.png",
    show_shapes=True,
    show_layer_names=True,
    rankdir="TB",
    expand_nested=False,
    dpi=96,
)
model.fit(train_x,train_y,batch_size=512,epochs=3,verbose=2)

In [ ]:
from PIL import Image 
import matplotlib.pyplot as plt
im = Image.open("simple_model.png") 
im.show()
plt.show()

In [ ]:
from keras.preprocessing.sequence import pad_sequences
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
maxlen=1000
max_features=5000 
embed_size=300

train_sample=train_df['review']

#Tokenizing steps- must be remembered
tokenizer=Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(train_sample))
train_sample=tokenizer.texts_to_sequences(train_sample)

#Pad the sequence- To allow same length for all vectorized words
train_sample=pad_sequences(train_sample,maxlen=maxlen)



EMBEDDING_FILE = '../input/wikinews300d1msubwordvec/wiki-news-300d-1M-subword.vec'
def get_coefs(word,*arr): return word, np.asarray(arr, dtype='float32')
embeddings_index = dict(get_coefs(*o.split(" ")) for o in open(EMBEDDING_FILE) if len(o)>100)

all_embs = np.stack(embeddings_index.values())
emb_mean,emb_std = all_embs.mean(), all_embs.std()
embed_size = all_embs.shape[1]

word_index = tokenizer.word_index
nb_words = min(max_features, len(word_index))
embedding_matrix = np.random.normal(emb_mean, emb_std, (nb_words, embed_size))
for word, i in word_index.items():
    if i >= max_features: continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None: embedding_matrix[i] = embedding_vector
plt.plot(embedding_matrix[20])
plt.show()

In [ ]:
from keras.preprocessing.sequence import pad_sequences
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
maxlen=1000
max_features=5000 
embed_size=300

train_sample=question_df['lst2Tite'][1:121:2]

#Tokenizing steps- must be remembered
tokenizer=Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(train_sample))
train_sample=tokenizer.texts_to_sequences(train_sample)

#Pad the sequence- To allow same length for all vectorized words
train_sample=pad_sequences(train_sample,maxlen=maxlen)



EMBEDDING_FILE = '../input/glove-global-vectors-for-word-representation/glove.6B.50d.txt'
def get_coefs(word,*arr): return word, np.asarray(arr, dtype='float32')
embeddings_index = dict(get_coefs(*o.split(" ")) for o in open(EMBEDDING_FILE) if len(o)>100)

all_embs = np.stack(embeddings_index.values())
emb_mean,emb_std = all_embs.mean(), all_embs.std()
embed_size = all_embs.shape[1]

word_index = tokenizer.word_index
nb_words = min(max_features, len(word_index))
embedding_matrix = np.random.normal(emb_mean, emb_std, (nb_words, embed_size))
for word, i in word_index.items():
    if i >= max_features: continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None: embedding_matrix[i] = embedding_vector

        
        inp=Input(shape=(maxlen,))
z=Embedding(max_features,embed_size,weights=[embedding_matrix])(inp)
z=Bidirectional(LSTM(60,return_sequences='True'))(z)
z=GlobalMaxPool1D()(z)
z=Dense(16,activation='relu')(z)
z=Dense(1,activation='softmax')(z)
model=Model(inputs=inp,outputs=z)
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()
plot_model(
    model,
    to_file="glove_simple_model.png",
    show_shapes=True,
    show_layer_names=True,
    rankdir="TB",
    expand_nested=False,
    dpi=96,
)

model.fit(train_x,train_y,batch_size=128,epochs=3,verbose=2,validation_data=(val_x,val_y))